name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0" # Specify the version of Go to use. Adjust as needed.

      # Install dependencies
      - name: Install dependencies
        working-directory: ./2023
        run: pwd; go mod tidy

      # Run tests
      - name: Run tests
        working-directory: ./2023
        run: go test ./... -v

      # Optional: Collect test coverage (if desired)
      - name: Run tests with coverage
        working-directory: ./2023
        run: go test ./... -coverprofile=coverage.out

      # Upload test coverage results (if using coverage)
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: 2023/coverage.out # Ensure the correct path is used for the uploaded artifact
